# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Eugenio Mauri
email: eugeniomau96[at]gmail.com
work_email: eugenio.mauri[at]natixis.com
description: >- # this means to ignore newlines until "baseurl:"
  Write something
baseurl: "" # the subpath of your site, e.g. /blog
url: "eugeniomauri1.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#linkedin_username: 
github_username:  eugeniomauri1

social:
  linkedin_url: https://www.linkedin.com/in/eugenio-mauri/
  scholar_url_short: https://scholar.google.com/eugenio-mauri/
  scholar_url: https://scholar.google.com/citations?user=1HcLqqIAAAAJ&hl=en
  orchid_url: https://orcid.org/0000-0001-8100-3956

# Build settings
theme: minima
plugins:
  - jekyll-feed
  
header_pages:
  - index.markdown
  - projects.markdown
  - cv.markdown
  - contact.markdown
  
license:
  name: CC BY-SA 4.0
  url: https://creativecommons.org/licenses/by-sa/4.0/

footer:
  jekyll_url: https://jekyllrb.com
  jekyll_name: Jekyll
  theme_url: https://github.com/jekyll/minima
  theme_name: minima

ref_color: 00A86B

personal_photo:
  address: '/assets/images/myphoto.jpg'
  caption: 'Welcome to my personal web page!'

  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
